"""rename addres
Revision ID: 895320cdc369
Revises: fc68833a4930
Create Date: 2024-06-30 11:37:12.974438
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '895320cdc369'
down_revision = 'fc68833a4930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###